services:
  - type: worker
    name: doompy-matchmaking
    runtime: python
    rootDir: Python-DOOM-master
    buildCommand: echo "no build needed"
    startCommand: python server.py
    plan: free
    envVars:
      - key: PORT
        value: 9999
